name: "Maintain tag (version) PR comment"

on:
  push:
    tags:
      - "v*"
    branches:
      - qa
      - test

jobs:
  update-tag-pr-comment:
    runs-on: ubuntu-latest
    # TODO: this is obviously broken
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # used by GitVersion to find the most recent tag outside of this branch

      - name: Get next version
        uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          scheme: semver
          increment: patch

      - name: "Create or update tag/version PR comment"
        uses: im-open/update-pr-comment@v1.1.3
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-identifier: "current-tag"
          comment-content: "ðŸ•” This PR currently contains the tag: ${{ steps.version.outputs.v-version }} which supersedes ${{ steps.version.outputs.current-v-version }}"
