name: "Update branch"

on:
  push:
    branches:
      - main
      - test

jobs:
  rebase-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update (rebase) test and dev branch
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        run: |
          git checkout test
          git rebase main test
          git push origin test

          git checkout dev
          git rebase test dev
          git push origin dev

      - name: Update (rebase) dev branch
        if: github.ref == 'refs/heads/test'
        continue-on-error: true
        run: |
          git checkout dev
          git rebase test dev
          git push origin dev
